spring:
  application:
    name: assesment
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL:phi3:mini}
      embedding:
        options:
          model: ${OLLAMA_EMBED_MODEL:nomic-embed-text}
llm:
  provider: ${LLM_PROVIDER:ollama}
